**Strassen Matrix**

In [5]:
import numpy as np
def split(matrix):
  row,col=matrix.shape
  row2,col2=row//2,col//2
  return matrix[:row2,:col2],matrix[:row2,col2:],matrix[row2:,:col2],matrix[row2:,col2:]
def Strassen(A,B):
  if A.shape == (1,1):
    return A*B

  #split matrices into quadrants
  A11,A12,A21,A22=split(A)
  B11,B12,B21,B22=split(B)

  #Compute the 7 products
  M1 = Strassen(A11+A22,B11+B22)
  M2 = Strassen(A21+A22,B11)
  M3 = Strassen(A11,B12-B22)
  M4 = Strassen(A22,B21-B11)
  M5 = Strassen(A11+A12,B22)
  M6 = Strassen(A21-A11,B11+B12)
  M7 = Strassen(A12-A22,B21+B22)

  #calculate the result submatrices
  C11 = M1+M4-M5+M7
  C12 = M3+M5
  C21 = M2+M4
  C22 = M1-M2+M3+M6

  #combine submatrices into one result matrix
  top = np.hstack((C11,C12))
  bottom = np.hstack((C21,C22))
  return np.vstack((top,bottom))

#Function to multiply two 4*4 matrices using Strassen's Algorithm
def multiply_strassen_4x4(A,B):
  assert A.shape == (4,4) and  B.shape == (4,4) , " both Matrices must be 4x4"
  return Strassen(A,B)

#Example 4x4 matrices
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
B = np.array([[16,15,14,13],
              [12,11,10,9],
              [8,7,6,5],
              [4,3,2,1]])

#Multiply the matrices using Strassen's Algorithm
result=multiply_strassen_4x4(A,B)
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\n Result of Strassen's matrix Multiplication:")
print(result)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix B:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

 Result of Strassen's matrix Multiplication:
[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]
